# ================================
# ? COMMON SETTINGS
# ================================
spring.application.name=BookingApp

# ? Tu sa prepína prostredie
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Common Hibernate / Mail defaults
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.output.ansi.enabled=ALWAYS
