server {
    listen 443 ssl http2;
    server_name bookingapp.gloziksoft.sk;

    ssl_certificate     /etc/letsencrypt/live/bookingapp.gloziksoft.sk/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bookingapp.gloziksoft.sk/privkey.pem;

    # ACME
    location /.well-known/acme-challenge/ {
        root /var/www/html;
        allow all;
    }

    # ===============================
    # SPRING BOOT
    # ===============================
    location / {
        proxy_pass http://localhost:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

#############################################
# HTTP → HTTPS
#############################################
server {
    listen 80;
    server_name bookingapp.gloziksoft.sk;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
        allow all;
    }

    return 301 https://$host$request_uri;
}
